### ISSUE TITLE
ABOR

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#26]
Hello,

[16:18:49] [R] RETR [TTT] - ( 4M 1F - COMPLETE ) - [TTT]
[16:18:49] [R] 550 [TTT] - ( 4M 1F - COMPLETE ) - [TTT]: Permission denied.
[16:18:52] [L] 426 Connection closed; transfer aborted.
[16:18:52] [L] 226 ABOR command successful

org.drftpd.commands.dataconnection.DataConnectionHandler  - IOException during transfer
org.drftpd.slave.TransferFailedException: Read timed out
at org.drftpd.master.RemoteTransfer.getTransferStatus(RemoteTransfer.java:104)
at org.drftpd.master.TransferState.getTransferStatus(TransferState.java:356)
at org.drftpd.commands.dataconnection.DataConnectionHandler.transfer(DataConnectionHandler.java:990)
at org.drftpd.commands.dataconnection.DataConnectionHandler.doSTOR(DataConnectionHandler.java:1128)
at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
at org.drftpd.master.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:611)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

The source file has only w-w-w rights, is it possible to fix this problem? DRFTPD should just refuse the transfer, move on file and continue the transfer but that it completely closes the connection.

Thx!

**Comment by zer0c0nf** [comment]
Fixed 👍 

# Only allow filenames with the defined allowed chars 
uploadex ([^/a-z0-9()._-]) !*

# Only allow dirnames with the defined allowed chars 
makedirex ([^/a-z0-9()._-]) !*
