### ISSUE TITLE
Error with Java 8

### ISSUE THREAD

**Issue by zer0c0nf** [drftpd-ng/drftpd3#4]
Hello,

I've error with java 8, obtain error : XML.

Error loading drftpd
org.drftpd.usermanager.UserFileException: Error loading drftpd
at org.drftpd.usermanager.javabeans.BeanUserManager.getUserByNameUnchecked(BeanUserManager.java:109)
at org.drftpd.usermanager.AbstractUserManager.getUserByNameIncludeDeleted(AbstractUserManager.java:179)
at org.drftpd.commands.login.LoginHandler.doUSER(LoginHandler.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
at org.drftpd.master.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:611)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: org.drftpd.usermanager.UserFileException: Error loading drftpd
at org.drftpd.usermanager.javabeans.BeanUserManager.loadUser(BeanUserManager.java:135)
at org.drftpd.usermanager.javabeans.BeanUserManager.getUserFromSoftReference(BeanUserManager.java:165)
at org.drftpd.usermanager.javabeans.BeanUserManager.getUserByNameUnchecked(BeanUserManager.java:104)
... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
at java.beans.XMLDecoder.readObject(Unknown Source)
at org.drftpd.usermanager.javabeans.BeanUserManager.loadUser(BeanUserManager.java:128)
... 13 more

Thx!

**Comment by zer0c0nf** [comment]
Java 9 working... but flood error in console.

[23:42:30] [R] En train de se connecter à 127.0.0.1 -> IP=127.0.0.1 PORT=2121
[23:42:30] [R] Connecté à 127.0.0.1
[23:42:30] [R] 220 DrFTPD 3.0.0 http://drftpd.org
[23:42:30] [R] AUTH TLS
[23:42:30] [R] 234 auth TLS successful
[23:42:30] [R] TLSv1.2 la négociation est établie...
[23:42:30] [R] TLSv1.2 session chiffrée à l'aide de chiffrement ECDHE-RSA-AES256-GCM-SHA384 (256 bits)
[23:42:30] [R] PBSZ 0
[23:42:30] [R] 200 Command okay
[23:42:30] [R] USER drftpd
[23:42:30] [R] 331 Password required for drftpd.
[23:42:30] [R] PASS (hidden)
[23:42:30] [R] 230- 
[23:42:30] [R] 230-         Welcome to the future of FXP:ing


jvm 1    | janv. 17, 2016 11:29:12 PM sun.util.PropertyResourceBundleCharset$PropertiesFileDecoder decodeLoop
jvm 1    | INFOS: Invalid or unmappable UTF-8 sequence detected. Switching encoding from UTF-8 to ISO-8859-1
jvm 1    | janv. 17, 2016 11:29:12 PM sun.util.PropertyResourceBundleCharset$PropertiesFileDecoder decodeLoop
jvm 1    | INFOS: Invalid or unmappable UTF-8 sequence detected. Switching encoding from UTF-8 to ISO-8859-1
jvm 1    | Exception in thread "CommitHandler" java.lang.StackOverflowError
jvm 1    |      at java.lang.Exception.<init>(Exception.java:102)
jvm 1    |      at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
jvm 1    |      at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
jvm 1    |      at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:520)
jvm 1    |      at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
jvm 1    |      at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
jvm 1    |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(Method.java:520)
jvm 1    |      at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:261)
jvm 1    |      at java.beans.Statement.invokeInternal(Statement.java:292)
jvm 1    |      at java.beans.Statement.access$000(Statement.java:58)
jvm 1    |      at java.beans.Statement$2.run(Statement.java:185)
jvm 1    |      at java.security.AccessController.doPrivileged(Native Method)

**Comment by surfaace** [comment]
known issue with java. http://bugs.java.com/view_bug.do?bug_id=6542811

**Comment by zer0c0nf** [comment]
any solution? :)

**Comment by zer0c0nf** [comment]
jvm 1    | Application start failed.
jvm 1    | java.lang.NoClassDefFoundError: org/drftpd/vfs/InodeHandleInterface
jvm 1    |      at java.lang.ClassLoader.defineClass1(java.base@9-ea/Native Method)
jvm 1    |      at java.lang.ClassLoader.defineClass(java.base@9-ea/ClassLoader.java:942)
jvm 1    |      at java.security.SecureClassLoader.defineClass(java.base@9-ea/SecureClassLoader.java:150)
jvm 1    |      at java.net.URLClassLoader.defineClass(java.base@9-ea/URLClassLoader.java:467)
jvm 1    |      at java.net.URLClassLoader.access$100(java.base@9-ea/URLClassLoader.java:78)
jvm 1    |      at java.net.URLClassLoader$1.run(java.base@9-ea/URLClassLoader.java:375)
jvm 1    |      at java.net.URLClassLoader$1.run(java.base@9-ea/URLClassLoader.java:369)
jvm 1    |      at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
jvm 1    |      at java.net.URLClassLoader.findClass(java.base@9-ea/URLClassLoader.java:368)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadLocalClass(StandardPluginClassLoader.java:413)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:482)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:390)
jvm 1    |      at org.java.plugin.drftpd.SynchronizedPluginClassLoader.loadClass(SynchronizedPluginClassLoader.java:61)
jvm 1    |      at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
jvm 1    |      at java.lang.ClassLoader.defineClass1(java.base@9-ea/Native Method)
jvm 1    |      at java.lang.ClassLoader.defineClass(java.base@9-ea/ClassLoader.java:942)
jvm 1    |      at java.security.SecureClassLoader.defineClass(java.base@9-ea/SecureClassLoader.java:150)
jvm 1    |      at java.net.URLClassLoader.defineClass(java.base@9-ea/URLClassLoader.java:467)
jvm 1    |      at java.net.URLClassLoader.access$100(java.base@9-ea/URLClassLoader.java:78)
jvm 1    |      at java.net.URLClassLoader$1.run(java.base@9-ea/URLClassLoader.java:375)
jvm 1    |      at java.net.URLClassLoader$1.run(java.base@9-ea/URLClassLoader.java:369)
jvm 1    |      at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
jvm 1    |      at java.net.URLClassLoader.findClass(java.base@9-ea/URLClassLoader.java:368)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadLocalClass(StandardPluginClassLoader.java:413)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:482)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:390)
jvm 1    |      at org.java.plugin.drftpd.SynchronizedPluginClassLoader.loadClass(SynchronizedPluginClassLoader.java:61)
jvm 1    |      at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
jvm 1    |      at org.drftpd.GlobalContext.<clinit>(GlobalContext.java:101)
jvm 1    |      at org.drftpd.master.ConnectionManager.boot(ConnectionManager.java:95)
jvm 1    |      at org.drftpd.master.Boot.startApplication(Boot.java:41)
jvm 1    |      at org.java.plugin.boot.Boot.boot(Boot.java:346)
jvm 1    |      at org.java.plugin.boot.Boot.main(Boot.java:243)
jvm 1    |      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
jvm 1    |      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
jvm 1    |      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
jvm 1    |      at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:533)
jvm 1    |      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
jvm 1    |      at java.lang.Thread.run(java.base@9-ea/Thread.java:843)
jvm 1    | Caused by: java.lang.ClassNotFoundException: class org.drftpd.vfs.InodeHandleInterface is not visible for plug-in master, no filter found for library file:/C:/Users/admin/Downloads/drftpd3-develop/drftpd3-develop/.jpf_shadow/slave@3.2.0/slave-3.2.0.jar
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.checkClassVisibility(StandardPluginClassLoader.java:629)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:484)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadPluginClass(StandardPluginClassLoader.java:497)
jvm 1    |      at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:390)
jvm 1    |      at org.java.plugin.drftpd.SynchronizedPluginClassLoader.loadClass(SynchronizedPluginClassLoader.java:61)
jvm 1    |      at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
jvm 1    |      ... 39 more
wrapper  | <-- Wrapper Stopped

**Comment by zer0c0nf** [comment]
Its ok. 15UPTIME: Master has been online for 35d 19h

Good work! :)

**Comment by donmagic1** [comment]
[AsyncCommandHandler - class org.drftpd.slave.async.AsyncCommandArgument] org.drftpd.protocol.slave.SlaveProtocolCentral  - Invokation failed due to: public org.drftpd.slave.async.AsyncResponse org.drftpd.protocol.slave.def.BasicHandler.handleSend(org.drftpd.slave.async.AsyncCommandArgument)
java.lang.NullPointerException
	at org.drftpd.slave.Slave.sendResponse(Slave.java:685)
	at org.drftpd.slave.Transfer.transfer(Transfer.java:445)
	at org.drftpd.slave.Transfer.sendFile(Transfer.java:338)
	at org.drftpd.protocol.slave.def.BasicHandler.handleSend(BasicHandler.java:764)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:171)
	at org.drftpd.slave.Slave.handleCommand(Slave.java:561)
	at org.drftpd.slave.Slave.access$200(Slave.java:73)
	at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:602)
	at java.lang.Thread.run(Thread.java:748)

so how do you fixed it?
