### ISSUE TITLE
SITE NEW comparision issue

### ISSUE THREAD

**Issue by Scitz0** [drftpd-ng/drftpd3#61]
`java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:439)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.drftpd.commands.newhandler.New.doNEW(New.java:131)
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
	at org.drftpd.master.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:611)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Seems newer java uses a new sort algorithm(TimSort) that report these errors where previous sort method did not.

Can be solved by adding wrapper.java.additional.x=-Djava.util.Arrays.useLegacyMergeSort=true
But doesn't really solve the problem. 

The Comparator that throws the error is https://github.com/drftpd-ng/drftpd3/blob/master/src/plugins/org.drftpd.commands.newhandler/src/org/drftpd/commands/newhandler/New.java#L165

**Comment by Scitz0** [comment]
Seems to be fixed in later jdk8 versions, 1.8.0_112 is verified to work without the extra -Djava.util.Arrays.useLegacyMergeSort=true setting
