### ISSUE TITLE
Slave remerge issues

### ISSUE THREAD

**Issue by donmagic1** [drftpd-ng/drftpd3#69]
When new slaves created and raced some files on it after ./slave.sh restart slaves never comes up it get errors 

Slave seems to have gone offline, have not received a response in 60065 milliseconds. ·
ON2 error: null. ·
ON2 Slave went offline while processing command. ·

if i delete files on that slave it merge fast and comes up untill next reboot

DEBUG 2017-05-11 00:24:21,152 [Slave Main Thread] org.drftpd.slave.Slave  - Slave wrote response - org.drftpd.slave.async.AsyncResponseDiskStatus[status=org.drftpd.sla$
DEBUG 2017-05-11 00:24:21,153 [Slave Main Thread] org.drftpd.slave.Slave  - Lost connection to the master, may have been kicked offline
DEBUG 2017-05-11 00:24:36,455 [Slave Main Thread] org.drftpd.slave.Slave  - Slave fetched org.drftpd.slave.async.AsyncCommand[index=fe,name=ping]
DEBUG 2017-05-11 00:24:36,456 [AsyncCommandHandler - class org.drftpd.slave.async.AsyncCommand] org.drftpd.slave.Slave  - Slave wrote response - org.drftpd.slave.async$
DEBUG 2017-05-11 00:24:46,466 [Slave Main Thread] org.drftpd.slave.Slave  - Slave fetched org.drftpd.slave.async.AsyncCommand[index=fe,name=ping]
DEBUG 2017-05-11 00:24:46,467 [AsyncCommandHandler - class org.drftpd.slave.async.AsyncCommand] org.drftpd.slave.Slave  - Slave wrote response - org.drftpd.slave.async$
DEBUG 2017-05-11 00:24:56,477 [Slave Main Thread] org.drftpd.slave.Slave  - Slave fetched org.drftpd.slave.async.AsyncCommand[index=fe,name=ping]
DEBUG 2017-05-11 00:24:56,478 [AsyncCommandHandler - class org.drftpd.slave.async.AsyncCommand] org.drftpd.slave.Slave  - Slave wrote response - org.drftpd.slave.async$
DEBUG 2017-05-11 00:25:06,493 [Slave Main Thread] org.drftpd.slave.Slave  - Lost connection to the master, may have been kicked offline

**Comment by donmagic1** [comment]
ERROR 2017-05-11 00:48:41,172 [RemoteSlave - ON2] org.drftpd.master.RemoteSlave  - Ping lost, no response from slave, sending new ping to slave
ERROR 2017-05-11 00:48:51,183 [RemoteSlave - ON2] org.drftpd.master.RemoteSlave  - Ping lost, no response from slave, sending new ping to slave
DEBUG 2017-05-11 00:49:00,124 [RemoteSlave - ON1] org.drftpd.master.RemoteSlave  - Received: org.drftpd.slave.async.AsyncResponse[index=ff]
DEBUG 2017-05-11 00:49:01,189 [RemoteSlave - ON2] org.drftpd.master.RemoteSlave  - setOffline() Slave seems to have gone offline, have not received a response in 60058$
DEBUG 2017-05-11 00:49:01,189 [RemoteSlave - ON2] org.drftpd.master.RemoteSlave  - setOffline() error: null
ERROR 2017-05-11 00:49:01,189 [RemoteSlave - ON2] org.drftpd.master.RemoteSlave  -
org.drftpd.exceptions.SlaveUnavailableException
        at org.drftpd.master.RemoteSlave.run(RemoteSlave.java:866)
        at java.lang.Thread.run(Thread.java:748)
INFO 2017-05-11 00:49:02,143 [RemoteSlaveRemerge - ON2] org.drftpd.master.RemoteSlave  - setOffline()
org.drftpd.exceptions.SlaveUnavailableException: Slave went offline while processing command
        at org.drftpd.master.RemoteSlave.fetchResponse(RemoteSlave.java:782)
        at org.drftpd.master.RemoteSlave.initializeSlaveAfterThreadIsRunning(RemoteSlave.java:438)
        at org.drftpd.master.RemoteSlave.access$000(RemoteSlave.java:86)
        at org.drftpd.master.RemoteSlave$1InitiateRemergeThread.run(RemoteSlave.java:689)
        at java.lang.Thread.run(Thread.java:748)
DEBUG 2017-05-11 00:49:14,500 [CommitHandler] org.drftpd.master.RemoteSlave  - Wrote slavefile for ON2

**Comment by donmagic1** [comment]
need reboot box 👍
