### ISSUE TITLE
MP3 problem

### ISSUE THREAD

**Issue by donmagic1** [drftpd-ng/drftpd3#77]
DEBUG 2017-07-24 03:54:36,227 [AsyncCommandHandler - class org.drftpd.slave.async.AsyncCommandArgument] org.drftpd.slave.Slave  - 
java.io.IOException: 05-marco-portwein-powder.mp3 is not a valid MP3 file
	at org.drftpd.protocol.zipscript.mp3.slave.MP3Parser.getMP3Info(MP3Parser.java:65)
	at org.drftpd.protocol.zipscript.mp3.slave.ZipscriptMP3Handler.getMP3File(ZipscriptMP3Handler.java:53)
	at org.drftpd.protocol.zipscript.mp3.slave.ZipscriptMP3Handler.handleMP3File(ZipscriptMP3Handler.java:45)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:171)
	at org.drftpd.slave.Slave.handleCommand(Slave.java:561)
	at org.drftpd.slave.Slave.access$200(Slave.java:73)
	at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:602)
	at java.lang.Thread.run(Thread.java:748)

**Comment by donmagic1** [comment]
it dont delete bad file on mp3

**Comment by donmagic1** [comment]
https://imgur.com/a/x9kvr

**Comment by donmagic1** [comment]
same problem with rar files 1KB remains unchanged not deleted

**Comment by zc0nf** [comment]
Maybre related 

`[Listening for slave connections - org.drftpd.master.SlaveManager@6ec9ad60] org.drftpd.master.SlaveManager  - 
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.drftpd.master.SlaveManager.run(SlaveManager.java:405)
	at java.lang.Thread.run(Thread.java:748)`

Thx @donmagic1

**Comment by epochyx** [comment]
Can you please provide:
- Java version
- OS
And a clear scenario to reproduce the bug?

**Comment by donmagic1** [comment]
java 8, 
ubuntu 16.04
when uploading mp3 file, you get same size as sfv, it stays there as completed, but its bad file.

**Comment by zc0nf** [comment]
Hello,
@maxpayneovh @mvangoor @epochyx 
Is the problem still current?

**Comment by tsautier** [comment]
@mvangoor @epochyx for review
