### ISSUE TITLE
The RootDirectory does not have a section

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd3#86]
Conditions :

Fresh install
JDK 8
Windows 64 Bits

LOG:

`INFO   | jvm 1    | 2019/01/20 10:38:04 | ERROR FtpConn thread 60 from 127.0.0.1 - pool-29-thread-1 org.drftpd.commandmanager.StandardCommandManager - Command mlsd failed: ''
INFO   | jvm 1    | 2019/01/20 10:38:04 | java.lang.IllegalStateException: The RootDirectory does not have a section
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.sections.def.SectionManager.lookup(SectionManager.java:93)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.plugins.mediainfo.list.MediaInfoList.addElements(MediaInfoList.java:91)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.commands.list.ListHandler.list(ListHandler.java:239)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.commands.list.ListHandler.doMLSD(ListHandler.java:137)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at org.drftpd.master.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:598)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/01/20 10:38:04 | 	at java.lang.Thread.run(Thread.java:748)`

and 

`INFO   | jvm 1    | 2019/01/20 10:38:08 | DEBUG CommitHandler org.drftpd.vfs.VirtualFileSystem - Wrote fullPath userdata/vfs//.dirProperties`   

double slash???

master.conf
`sectionmanager=org.drftpd.sections.def`

**Comment by zc0nf** [comment]
Fixed by https://github.com/drftpd-ng/drftpd3/pull/96
